### ISSUE TITLE
Allow team creation with just a Job and skills

### ISSUE THREAD

**Issue by nnguyen259** [jedmund/hensei-web#84] opened 2022-12-28 18:05 UTC
Step to reproduce:

- Create a new party, the url at this point doesn't have a team id on it (i.e just app.granblue.team)
- Go to the character tab, select a mc class

Expected result: MC portrait and default skills are populated

Actual result: Only the portrait is populated, skills aren't. You also cannot select and pick any skill

Workaround:

- Select a party character first, which change the url to a unique id, at which point mc skill selection will work again

**Comment by jedmund** [comment] 2022-12-29 06:36
I literally just came to make this issue. I was working on https://github.com/jedmund/hensei-web/issues/61 and I figured out that the issue is that because parties are "created" when a character, summon, or weapon is selected, skills won't save because the party won't exist yet.

There's a few avenues to fix, but now that I know what's going on I should be able to get it done pretty quickly.

Thanks for the report!

**Comment by jedmund** [comment] 2023-01-08 09:38
Fixed in #139

**Closed by jedmund** 2023-01-08 09:38 UTC
Labels: bug, priority: high
