### ISSUE TITLE
Problem with weapon searching

### ISSUE THREAD

**Issue by 9highwind** [jedmund/hensei-web#277] opened 2023-03-18 19:41 UTC
I'm not sure how to phrase it but when searching for weapons, things look weird. The search doesn't look for the whole phrase, and not all weapons containing the string show up. My first guess is that it's looking for things that contain "scythe" OR "of", not the string "scythe of". 

<img width="710" alt="Screenshot 2023-03-18 at 12 37 48 PM" src="https://user-images.githubusercontent.com/128256125/226133763-fb82a3f5-b784-4eef-b9d7-af4ae17ced5e.png">
<img width="710" alt="Screenshot 2023-03-18 at 12 38 34 PM" src="https://user-images.githubusercontent.com/128256125/226133795-f1f37c26-2c50-4b7e-8899-91535d11bf43.png">
<img width="698" alt="Screenshot 2023-03-18 at 12 38 47 PM" src="https://user-images.githubusercontent.com/128256125/226133806-289f6e2c-32c9-4b15-bc0c-22ef807b7270.png">
<img width="698" alt="Screenshot 2023-03-18 at 12 39 03 PM" src="https://user-images.githubusercontent.com/128256125/226133820-a5ed2159-d950-41e5-b694-8bdb3cffd927.png">
<img width="698" alt="Screenshot 2023-03-18 at 12 39 28 PM" src="https://user-images.githubusercontent.com/128256125/226133841-3acf565b-5dd1-453e-b0f5-125603e1af66.png">
<img width="698" alt="Screenshot 2023-03-18 at 12 40 12 PM" src="https://user-images.githubusercontent.com/128256125/226133865-a3516ef1-643f-4422-9faa-52e219c776ca.png">

**Comment by jedmund** [comment] 2023-06-21 11:08
I know about this and it's a problem in how I am using the specific search algorithm I'm using. Unfortunately, I don't know how to fix it.

**Comment by jedmund** [comment] 2023-07-06 11:10
Ok I have a better idea of how to fix this. I'm going to close this as a duplicate of #33

**Closed by jedmund** 2023-07-06 11:10 UTC
Labels: priority: low
